name: Check build after pull request on master

on: 
  push:
    branches:
      - master

jobs:
  masterbuilder:
    runs-on: self-hosted
    container:
      image: obspher/ubuntu-dev:1.1.4
      env:
        CONAN_USER_HOME: /home/conan
      volumes:
        - /home/obs-vision/github/conan:/home/conan
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Check stability
        run: bash -c "! grep -P "@obspher/dev" conanfile.py"

      - name: Create build directory
        run: mkdir build

      - name: Conan remote
        run: conan remote add origin https://obspherit.jfrog.io/artifactory/api/conan/default-conan

      - name: Conan user
        run: export CONAN_REVISIONS_ENABLED=1;conan user -p cmVmdGtuOjAxOjE3MTIxNDg1NTI6WEJSV25hM0NXRkFQZkdtNmhJMldzRXRHelV5 -r origin obspher@obspher.com

      - name: Install conan dependencies
        working-directory: ./build
        run: export CONAN_REVISIONS_ENABLED=1;conan install .. --build missing --build cascade --update

      - name: Build package
        working-directory: ./build
        run: export CONAN_REVISIONS_ENABLED=1;conan build ..

      - name: Static analysis
        run:  cppcheck src/ -Iinclude/ --error-exitcode=1 --enable=all --std=c++20 --inline-suppr

      - name: Dynamic analysis on unit tests
        run: echo valgrind --leak-check=full --show-reachable=yes --trace-children=yes --error-exitcode=33 ./build/bin/unit_test

      - name: Get conan package name
        id: conan_infos
        run: |
          echo "::set-output name=name::$(conan inspect . --raw name)\n"
          echo "::set-output name=version::$(conan inspect . --raw version)\n"

      - name: Export conan package
        run: export CONAN_REVISIONS_ENABLED=1;conan export-pkg . -bf ./build -f

      - name: Conan create
        run: export CONAN_REVISIONS_ENABLED=1;conan create .

      - name: Upload on conan server
        run: export CONAN_REVISIONS_ENABLED=1;conan upload ${{steps.conan_infos.outputs.name}}/${{steps.conan_infos.outputs.version}}